version: '3.7'

services:

  example:
    container_name: angular-docker-prueba
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4200:4200'
    environment:
      - CHOKIDAR_USEPOLLING=true