version: '3.7'

services:

  example:
    container_name: angular-docker-production
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    