# base image
FROM node:16

# set working directory
WORKDIR /app

# add app
COPY . /app

# install and cache app dependencies
RUN npm install
RUN npm install -g @angular/cli

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

EXPOSE 4200

# start app
CMD ng serve --host 0.0.0.0